### ISSUE TITLE
[feature reqeust] Decode transaction from string

### ISSUE THREAD

**Issue by Tougee** [sol4k/sol4k#64]
May I ask what caused this [PR](https://github.com/sol4k/sol4k/pull/47) not to be merged, this feature seems quite useful. 
I've now forked the code, copied some of the code for this PR, and fixed a transaction serialization issue, if you're willing to merge this part of the code, I can PR for this. 

[decode transaction from string, fix transaction serialization bug](https://github.com/sol4k/sol4k/compare/main...Tougee:sol4k:main)

Thank you

**Comment by Shpota** [comment]
Hi @Tougee 

That PR needed addressing the code review comments. The code responsible for publishing Maven artefacts was removed and there were some other review comments. Later on the author closed it. 

Feel free to open a PR. I will review it and then we can merge it.

**Comment by Tougee** [comment]
Thanks for your response. 
Since the time I created this issue, there are already a bunch of code changes that break the current code structure, so maybe it's better not to try merging them into this repo.

**Comment by Shpota** [comment]
@Tougee your changes looked good. I saw just a couple of small adjustments that I would suggest to apply. Feel free to open the PR

**Comment by Tougee** [comment]
Hi @Shpota, the [PR](https://github.com/sol4k/sol4k/pull/65) is created now.
The bunch of the code changes I'm talking about are in this [repo](https://github.com/MixinNetwork/android-app/blob/master/app/src/main/java/org/sol4k/VersionedTransaction.kt), I think these changes do affect the structure of the project.

**Comment by Shpota** [comment]
@Tougee thank you, that's cool. Let's move forward with your PR and then maybe incorporate other changes. I will review the PR shortly (most likely later on today)

**Comment by Shpota** [comment]
@Tougee I reviewed the PR and added a couple of minor comments

**Comment by Tougee** [comment]
@Shpota thanks for your suggestions.
I want to say that the current code in this PR is not very good because it only parses legacy transactions.

**Comment by Shpota** [comment]
@Tougee yes, I saw you moved forward with Versioned Transactions. If you want, feel free to add them to sol4k and I will release them afterwards.

Thank you for applying the review changes, I will check them shortly and merge the PR. From the first glance, everything is ok. I only see [some linter/style checks failing](https://github.com/sol4k/sol4k/actions/runs/9072997265/job/24935015511?pr=65).

**Comment by Tougee** [comment]
Linter's issue updated.
Regarding the versioned transaction related code, I'd be happy to add it to sol4k, but I'm not sure how to add a large amount of code to this repo. The current versioned transaction code does not inherit from existing transactions, can you please give some advice?
Thank you.

**Comment by Shpota** [comment]
> The current versioned transaction code does not inherit from existing transactions

That's fine; it doesn't have to. Versioned transactions are different from legacy transactions, and web3.js separates them as well. Feel free to add them as is, and we can iterate from there. If there are breaking changes, we can push them to 0.5.0.

**Comment by Tougee** [comment]
Sounds good, I'll create a new PR after this is complete.

**Comment by Tougee** [comment]
@Shpota versioned transaction PR is coming, please take your time to review :)
https://github.com/sol4k/sol4k/pull/68
