### ISSUE TITLE
Exception Happens while generating KeyPair

### ISSUE THREAD

**Issue by Chandra-Sekhar-Bala** [sol4k/sol4k#98]
The version i am using: 
```
 implementation("org.sol4k:sol4k:0.5.3")
```
Error: 
<img width="693" alt="Solana" src="https://github.com/user-attachments/assets/f7efa36b-1fff-411b-96f1-7b6763f2fe39">

Android Studio version: 
``` Android Studio Koala Feature Drop | 2024.1.2 Patch 1 ```

**Comment by Shpota** [comment]
Hi @Chandra-Sekhar-Bala 

Could you please share your Gradle configuration?

These two dependencies should have loaded transitively, but they did not for some reason.
```
implementation 'org.sol4k:tweetnacl:0.1.6'
implementation 'org.sol4k:utilities:0.1.0'
``` 
Adding them manually will probably solve the issue, but that's only a workaround.

**Comment by Chandra-Sekhar-Bala** [comment]
Hey @Shpota,
My Kotlin version is 2.0.0. 
Here's [the gist](https://gist.github.com/Chandra-Sekhar-Bala/ed9e817c211a05adaa2b71f0e5d8b92f) for you reference.

**Comment by Shpota** [comment]
@Chandra-Sekhar-Bala I think the issue might be with the serialization plugin. You are using `1.8.20` and sol4k relies on `2.0.21`. Try updating your code to use the latest version of serialization. Or alternatively you can use an old version of sol4k, let's say `0.3.3`, that relies on the older version of serialization.

**Comment by Chandra-Sekhar-Bala** [comment]
Thanks @Shpota, 
Degrading version to ```0.3.3``` actually worked for me.
